gabordemooij/redbean

.gitignore
README.markdown
RedBeanPHP/R.php
composer.json

Hi,
few days ago i created a fork to include composer support: https://github.com/simirimia/redbean. At least for me it works, package is listed at packagist: https://packagist.org/packages/simirimia/redbean.
Here is the pull request with which composer support should work for your repository. The R class is added for convinience to make the usage more similar to your documentation, but is not neccessary for composer.
I just came along the short discussion about integrating composer support again and so I'll like to send you these changes. Hope it helps!
Regards,
Verena

composer.json 

---

testing/RedUNIT/Base/PullRequest530.php
testing/cli/runtests.php

Added Unit Test as requested in https://github.com/gabordemooij/redbean/pull/530

Added Unit Test

---

.gitignore

rb-mysql.php, rb-postgres.php and rb-sqlite.php wants to sync.

Ignore separate versions

---

README.markdown

Added clearer information about using the `R` alias with Composer.

Update Compose aliasing

---

RedBeanPHP/Driver/RPDO.php
RedBeanPHP/QueryWriter.php
RedBeanPHP/QueryWriter/CUBRID.php
RedBeanPHP/QueryWriter/MySQL.php
RedBeanPHP/QueryWriter/PostgreSQL.php
RedBeanPHP/QueryWriter/SQLiteT.php
RedBeanPHP/RedException/SQL.php
RedBeanPHP/Repository/Fluid.php
RedBeanPHP/Repository/Frozen.php
testing/RedUNIT/Base/Database.php

Was thinking of doing something like this to deal with the issues #575 and #576. Would need a bit more work:
But just to let you know what I was thinking of, and so we have something to discuss.

Throw an exception when load hits a lock timeout

---

.travis.yml

Also test RedBean with PHP 7.2.

Add PHP 7.2 to .travis.yml

---

README.markdown

Added information regarding the use of Models with RedBeanPHP and Composer.

Added Composer Model documentation

---

README.markdown

Link travis build status svg to travis build page

[doc] Link travis build status svg to travis build page

---

RedBeanPHP/Finder.php
RedBeanPHP/QueryWriter/AQueryWriter.php
testing/RedUNIT/Base/Dispense.php

This should fix https://github.com/gabordemooij/redbean/issues/611 the right way.
If I missed the reason for those checks in `findOrLike()` let me know.

Fix new count() behavior in PHP 7.2

---

RedBeanPHP/Adapter/DBAdapter.php

Regarding line 155-156, if it's like the famous $NULL = NULL I tried to remove before, I guess it won't work.
The switch case make things a bit faster though, even if it's just a little.

Small code optimization of getAssoc function

---

RedBeanPHP/BeanCollection.php
RedBeanPHP/Driver/RPDO.php
RedBeanPHP/OODBBean.php

Did it wherever it seemed possible (usually when the array wasn't use after the call).
Also made a couple of small code changes, not sure you'll like them.. Anyway, let me know ;)
I hope there isn't one of those sneaky return values that need to be a variable to be passed by reference or whatever... Well, if there is we'll at least be able to add a comment about it I guess.

Changed array_shift to reset

---

RedBeanPHP/OODBBean.php

Thought I'd better split my PRs, however small they are, as long as they interact with different stuff.

Code refactoring to bail out of parseJoin faster

---

RedBeanPHP/OODBBean.php

This one might be too much, not sure. I guess this would need to be benchmark to see if it's really better...

Refactoring import()

---

RedBeanPHP/OODBBean.php

See also: [Issue #651](https://github.com/gabordemooij/redbean/issues/651)

Allow models to provide a jsonSerialize return

---

RedBeanPHP/Facade.php

Docblocks were wrong. I guess website needs to reflect that too.

Update R::find() and R::findAll() docblocks

---

RedBeanPHP/Finder.php

Fix findMulti when escaping tables in the query

---

RedBeanPHP/OODB.php

Return type of the method findCollection is BeanCollection, however, annotation says it is array. Suggest changing it from array to BeanCollection.

Fix findCollection method annotation

---

RedBeanPHP/Finder.php

- own and shared list is now keyed
- It actually loaded the lists one query at a time

Fix map and nmMap

---

redbean_manual.html

As per issue #361 - added detail about PDO connection errors, as well as try/catch PDO connection sample code.

More info for troubleshooting PDO connection

---

redbean_manual.html

Provided wrong sample code in prior commit, this one is a tested working plain PDO code. Sorry Gabor! 🙏

 Corrected PDO connection code sample

---

RedBeanPHP/Facade.php

Unset the toolbox, after verifying it exists, on Facade::removeToolBoxByKey

Attempt to fix issue #723

---

RedBeanPHP/Util/Diff.php

This doesn't change much (anything) for very small list comparison but should improve the speed while comparing big lists as it doesn't loop over the `$others` array over and over again anymore.

Improve R::Diff() speed

---

RedBeanPHP/QueryWriter/AQueryWriter.php

Should fix #795 
Needs more tests but I honestly don't have much time at the moment :(

Fix SQL issue with Mysql/Mariadb

---

RedBeanPHP/Facade.php

Should mirror 'find' return type.

Fix incorrect return type for findForUpdate

---

RedBeanPHP/QueryWriter/AQueryWriter.php

@gabordemooij this is the first part of the feature we discussed about starting with #798.
It should work for `@joined` and `@own` syntax for now.
The bracket notation is used with the @ syntax we added in #781.
It allows you to specify an alias like you would do using `fetchAs()` or `alias()`.
If used with `@joined`, it will behave the same as `fetchAs()`, if used with `@own` it will behave like `alias`.
A few examples:
```php
/*
* The book table has a title, author_id and coauthor_id column.
* The person table has a name column.
*/
R::aliases([
'author' => 'person',
'coauthor' => 'person'
]);
```
----------
`@joined`
```php
// If we want to find all books from a specific author, we can already do it like this (because we declared global aliases, it matches author to person):
R::find( …
```

Add bracket notation for aliasing @ syntax

---

RedBeanPHP/Facade.php

For https://github.com/gabordemooij/redbean/issues/813

Break out create toolbox logic from addDatabase

---

RedBeanPHP/BeanHelper/SimpleFacadeBeanHelper.php
RedBeanPHP/Facade.php

Please see https://github.com/gabordemooij/redbean/issues/877

Better model prefixing for multi-database uses.

---

RedBeanPHP/Facade.php

There are probably a lot more places where this can be applied, this pull aims to be a stater to gradually integrate TypedModel.

Allow for TypedModel hints
