gabordemooij/redbean

README.markdown

I have written the installation process via composer in README.markdown file. So anyone can easily install RedBeanPHP via composer without finding the package from packagist.
And also put a link of manual install page (RedBeanPHP official site). Hope that will be helpful for user to install the RedBeanPHP.

Installation process has been written in readme file

---

RedBeanPHP/QueryWriter/PostgreSQL.php

getColumns() in PostgreSQL QueryWriter used to return columns for all
tables with the same names, even if outside the current schemas

fix PostgreSQL's getColumns()

---

RedBeanPHP/BeanHelper/SimpleFacadeBeanHelper.php

When using PhpStorm 10.0.3 and PHP 7.0.1 for linting I get his error on the rb.php file:
```"Function name must be callable - a string, Closure or class implementing __invoke, currently \RedBeanPHP\BeanHelper\closure"```
Turns out the fix is as easy as improving the documentation for the $factory parameter from closure to \Closure.
This way the IDE stops thinking RedBeanPHP is broken.

Improve $factory parameter documentation

---

RedBeanPHP/Repository.php
testing/RedUNIT/Base/Misc.php

In case we have SimpleModel elements when storing bean with lists the following error occurs:
PHP Catchable fatal error:  Object of class [MODEL_NAME] could not be converted to string in /opt/projects/php/sbm/back-end/vendor/gabordemooij/redbean/RedBeanPHP/Repository.php on line 108
So this patch will walk trough all items in the list and unbox() them in case they are simple models. That way it is no longer required to call unbox() when adding new items in the "shared" (or "own") bean lists.

Auto unbox() SimpleModel arrays

---

RedBeanPHP/OODBBean.php

Check if given property name is a field link and clear the linked object. That prevents the old value of field getting stored.
Consider the following code:
```php
R::setup(/*options*/);  
R::setAutoResolve(TRUE);  
$bean = R::load('type', 1); //Database table type has an attribute link that references another table
$bean->link_id = $submittedIDOfLinkedBean;  
R::store($bean);  
```
Then the `link` property eventually does not get updated, since `link` is set to the OODBBean of the old object and on `R::store($bean)` the `id`of `link` object is read and overwrites the change made to `link_id`.

Add check if $property is field link

---

RedBeanPHP/Facade.php

The convertToBean method returns a OODBBean object, right?

Minor fix to the internal documentation of Facade::convertToBean method

---

RedBeanPHP/OODBBean.php

Maybe there's a reason it's not done like this, or maybe I missed something.

Don't call getModelForBean() for every __call()

---

RedBeanPHP/Facade.php
RedBeanPHP/Finder.php

As said in the commits, the $sql parameter will allow to sort beans so that we get the one we want in case it finds one. For example:
```php
$bean = R::findOrCreate("bean", [ "user_id" => 1 ], " ORDER BY mycolumn DESC ");
```
The LIMIT 1 (using ```glueLimitOne()```) will make the SQL query much faster and make the script use less memory since we're only returning the first bean found.

Adding $sql parameter and LIMIT 1 to findOrCreate()

---

RedBeanPHP/Repository/Fluid.php

This expands the existing risk for race conditions -- maybe somebody else modified the schema since the last describe? -- but this change can reduce the number of DESCRIBE operations called for an INSERT by an order of magnitude if there are a lot of columns.

Do describe once per table instead of once per column.

---

RedBeanPHP/QueryWriter/AQueryWriter.php

When using R::tagged() or R::taggedAll() it added a 'count(`bean_type`.id)' property to the beans it returned, simply got rid of that.

Remove unnecessary count in SELECT

---

RedBeanPHP/Facade.php

This is especially useful when using multiple databases.
I'm first checking if $partialBeans is TRUE before calling usePartialBeans().
It's true that we could just call usePartialBeans() even if partialBeans is FALSE but I thought it would be a waste since it's FALSE by default. If change it to TRUE by default at some point (not sure this will ever happen) we'd have to reverse the check.
The docs and tests need to be updated to reflect the change.

Allow to specify partial beans in R::setup() and R::addDatabase()

---

RedBeanPHP/Facade.php

When you use R::addDatabase(), you can't set the beanHelper on the fly without having to do a R::selectDatabase() first because R::selectDatabase() will first call configureFacadeWithToolbox() which will remove the BeanHelper you've set yourself.

Prevent R::selectDatabase from changing BeanHelper

---

RedBeanPHP/OODBBean.php

Edit: goal of the PR changed see below.
~We break out of the do-while when we're ready to return something.~
~That way we only reset withSql, withParams (etc) once and then return the property.~
~It also fixes returning NULL as reference (see https://github.com/gabordemooij/redbean/pull/625).~
~I'm not sure you'll like this way of doing things so feel free to simply discard this PR.~

Refactoring some OODBBean functions to use clearModifiers()

---

RedBeanPHP/BeanCollection.php
RedBeanPHP/Cursor.php
RedBeanPHP/Cursor/NullCursor.php
RedBeanPHP/Cursor/PDOCursor.php

This PR allows to call `reset()` on a BeanCollection, fetching data again from the database and putting the cursor back to the first position.
Exemple:
```php
// Let's say we have a table "book" with 5 books named book1, book2, ...
// Get every books in a collection
$collection = R::findCollection( 'book' );
// Print books' names
print $collection->next()->name; // 'book1'
print $collection->next()->name; // 'book2'
// Change the 3rd book's name
$book3 = R::load( 'book', 3 );
$book3->name = 'notBook3';
R::store( $book3 );
// It isn't reflected because collection data as already been loaded
print $collection->next()->name; // 'book3'
// This fetches data from the database again and puts the cursor back at the start
$collection->reset();
// It's the same as doing this again
// $collection = …
```

Add a reset() function to BeanCollection

---

RedBeanPHP/Finder.php

It's a small quality of life feature that doesn't affect performance, so why not ? :)

Automatically trim types in findMulti()

---

RedBeanPHP/Driver/RPDO.php

This is just a mockup for #700 for us to discuss about.
The idea is to use it this way:
```php
$bean = R::findOne( 'bean', ' property = ? AND property2 = ? AND property3 = ? ', [
$value,
[ $value2, PDO::PARAM_INT ],
[ $value3, PDO::PARAM_STR ]
]);
```
It should work anywhere we are able to pass $bindings as an argument without issue.
Pinging some people: @gabordemooij @brtdv @marios88

Manually define bindings parameters type

---

RedBeanPHP/Facade.php

The method's @return annotation should be OODBean instead of RedBeanPHP\OODBean as it has been identified in the use statement at the top. Alternatively, \RedBeanPHP\OODBean could be used.

Fix annotation for convertToBean() method

---

RedBeanPHP/AssociationManager.php

In PHP this is fine:
```php
$a = false;
var_dump($a['id']); // NULL
```
The last commit changed what `GetRow()` returns so we now need to check for `$row` here and can't just try to get an undefined index from it.

Stop unassociation if association not found

---

RedBeanPHP/Facade.php
RedBeanPHP/QueryWriter/AQueryWriter.php

Here is my take on this.
I removed `clearCache` because we already have `flushCache`.
I just added an argument to prevent it from counting the cache if that's not needed.
Also moved the FOR UPDATE cache fix in `queryRecord` so that we don't have to wipe the whole cache for this.
Let me know what you think @gabordemooij

Don't always clear cache on find/load FOR UPDATE

---

RedBeanPHP/Facade.php
RedBeanPHP/QueryWriter/AQueryWriter.php
RedBeanPHP/Repository.php

This is a proposal for #736 
```php
$book = R::load( 'book', 1 );
R::trash( $book ); // Returns 1
// ------
$books = R::findAll( 'book' );
count( $books ); // Returns 8
R::trashAll( $books ); // Returns 8
// ------
$book = R::dispense( 'book' );
R::store( $book );
$page = R::dispense( 'page' ); // We don't store it
// This will return 1 since $page doesn't get trashed
R::trashAll( [ $book, $page ] );

Have trash/trashAll return number of deleted beans

---

RedBeanPHP/QueryWriter/AQueryWriter.php

This modifies makeSQLFromConditions so that it is able to add a `condition IS NULL` if the value linked to a property is NULL.
```php
R::findLike( 'book', [ 'title' => NULL ] );
// Previously would execute this query
// SELECT * FROM `books`
// Would now execute this query
// SELECT * FROM `books` WHERE `title` IS NULL
```
Technically, this breaks BC.
But I don't think anyone would actually pass NULL values to the $conditions argument directly and if there's special cases where it could happen, I'm sure they are very rare.
One of the special case that could exist somewhere I guess:
```php
$title = $_GET['title'] ?? NULL;
// If there's a title, load that specific book, otherwise list them all:
R::findLike( 'book', [ 'title' => $title ] );
```

Allow findLike (and the likes) to use "IS NULL" conditions

---

RedBeanPHP/OODBBean.php

R::load('type', $id) and R::dispense both are based on the load function in class Repository(Fluid/Frozen). It will call the dispense function at first and load some default values. When you load the default values, it will change the __info['changelist']. It is OK when just dispense a new bean but not OK when loading a record from the database especially you want to use partial bean mode later.
https://github.com/gabordemooij/redbean/issues/754

Try to fix the default values issue when loading records from the database in partial bean mode

---

RedBeanPHP/Facade.php
testing/RedUNIT/Blackhole/Plugins.php

The current implementation was allowing creating a plugin that starts with an number even though it would then be unusable as functions cannot start with a number in PHP and it would result in a parse error.
```php
// This works
R::ext( '911', function() {
print 'Call the police!';
});
// This throws a parse error
R::911();
```
I fixed that and, while not allowing the entirety of allowed unicode since it can create more errors, allowed the underscore as well.
I also modified the `__callStatic` function as we don't need to check the name if it is already registered and fixed related tests.

Fix range of allowed characters for plugin name

---

RedBeanPHP/QueryWriter/AQueryWriter.php

It doesn't make it totally foolproof, but it mitigates a bit more than it previously did.
Here is an example that wouldn't pass the test before:
```php
R::fancyDebug( TRUE );
$highway = R::findOne('highway', ' limitation IS NULL ');
// Debug would print the following:
// SELECT `highway`.*  FROM `highway`  WHERE  limitation IS NULL   -- keep-cache
// resultset: 2 rows
```

Improve the sql check in glueLimitOne

---

RedBeanPHP/Repository.php

Also adds some checks to $mask to whitelist the type of inputs allowed.
Usage example:
```php
$rows = R::getRow( 'SELECT book.*, COUNT(page.id) AS pages, COUNT(review.id) AS reviews... ' );
$book = R::convertToBean( 'book', $row, [ 'pages', 'reviews' ] );
$metadata = $book->getMeta( 'data.bundle' );
echo $metadata['pages'];
echo $metadata['reviews'];
```
It gives a bit more flexibility when working with SQL you don't have control over for example.
Let me know what you think about it.

Allow an array of values to be used as meta-mask

---

RedBeanPHP/OODBBean.php
RedBeanPHP/QueryWriter.php
RedBeanPHP/QueryWriter/AQueryWriter.php

In #767 I answered the question by stating that one should do the following:
```php
$whitelisted_users = R::find( 'user', ' JOIN `status` WHERE `status`.id = `user`.status_id AND `status`.whitelist = ? ', [ 1 ] );
```
And I thought, why not have the `@joined` shorthand also available in `find()` and such ?
I had to move it away from OODBBean (and the QueryWriter felt like the obvious choice) and I added it's to every type of non-custom query (which means none of the `get...()` etc) that only target 1 type of bean (which means none of the `...Related()`, `...Tagged()` etc).
Therefore, it is available for all functions that call `queryRecord()`, `queryRecordWithCursor()` and `queryRecordCount()`.
With this you can find the same beans as above by doing:
```php
$whitelisted_users = R::find( …
```

Move parseJoin to QueryWrite

---

RedBeanPHP/QueryWriter/AQueryWriter.php

Allows to write stuff like
`R::findOne( 'book', ' ORDER BY @joined.author.name ASC ');`
It also fixes the search for the `WHERE` keyword in writeJoin (now case insensitive).

Fix writeJoin /w query starting at ORDER+ clause

---

RedBeanPHP/QueryWriter.php
RedBeanPHP/QueryWriter/AQueryWriter.php

Ok so, here's my take on this.
The differences are:
- Should work for SQL written without space like `(@joined.owner.name=?)OR(@joined.owner.status=?)`
- Should work when joining the same table multiple times using aliases
- Shouldn't join a table that has already been joined (`@joined.owner.name = ? OR @joined.owner.own.dog.name = ?` should only join `owner` once)
- Probably still works for CTE, can't test so I'll wait for Travis

Allow chaining of joins with @ syntax

---

RedBeanPHP/QueryWriter/AQueryWriter.php

This adds a bracket notation for `@shared` syntax which acts like `via()`.
```php
/*
* Following the example from https://redbeanphp.com/index.php?p=/many_to_many
* Let's retrieve projects which Bob is linked to
*/
$projects = R::find('project', ' @shared.employee[via:participant].name LIKE ? ', ['Bob']);
```

Add via to brack notation for @ syntax

---

RedBeanPHP/OODBBean.php

Fixed documentation for export() for OODBBean to accurately reflect current implementation of whitelisting beans. The current documentation for `export()` reads as:
```
/**
* Exports the bean as an array.
* This function exports the contents of a bean to an array and returns
* the resulting array. Depending on the parameters you can also
* export an entire graph of beans, apply filters or exclude meta data.
*
* Usage:
*
* <code>
* $bookData = $book->export( TRUE, TRUE, FALSE, [ 'author' ] );
* </code>
*
* The example above exports all bean properties to an array
* called $bookData including its meta data, parent objects but without
* any beans of type 'author'.
*
* @param boolean $meta    set to TRUE if you want to export meta data as well
* @param boolean $parents set to TRUE if you want …
```

Fix documentation for filtering for bean export

---

RedBeanPHP/QueryWriter/MySQL.php

The ``$version`` variable in my MariaDB installation contains the string ``10.4.32-MariaDB``.
Because of the uppercase letter M, this was falsely detected as MySQL > 8, which broke the detection of integer fields and prevented MariaDB from modifying the schema in fluid mode (all integer fields were detected as ``C_DATATYPE_SPECIFIED``).

Fix MariaDB detection
